auth:
  username: admin
  password: Ww110120..
projects:
- name: PIXROOT-API
  path: /www/wwwroot/inscription-api
  description: 版本管理测试项目
  enabled: true
- name: CHAIN-API
  path: /www/wwwroot/chain-api
  description: 原链接口
  enabled: true
- name: TEST
  path: /www/wwwroot/test
  description: TEST
  enabled: true
- name: TEST2
  path: /www/wwwroot/test2
  description: TEST2
  enabled: true
