---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/typescript
  - prettier
env:
  browser: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - react
  - import
settings:
  react:
    version: detect
rules:
  consistent-return: error
  default-case: error
  default-param-last: error
  no-loop-func: off
  arrow-body-style: [error, as-needed]

  import/no-useless-path-segments: error
  import/group-exports: off
  import/extensions: [error, never]
  import/no-duplicates: error
  import/first: error
  import/no-unused-modules: error

  react/jsx-key: error
  react/jsx-pascal-case: error
  react/destructuring-assignment: off
  react/function-component-definition: off
  react/no-array-index-key: error
  react/no-deprecated: off
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unknown-property: error
  react/prefer-stateless-function: off
  react/prop-types: off

  "@typescript-eslint/require-await": off
  "@typescript-eslint/restrict-template-expressions": off

  "@typescript-eslint/array-type": [error, {default: array-simple}]
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/consistent-type-assertions": [error, {assertionStyle: as}]

  "@typescript-eslint/no-extra-non-null-assertion": error
  "@typescript-eslint/no-inferrable-types": error
  "@typescript-eslint/no-this-alias": error
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/prefer-readonly": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-floating-promises": off
  "@typescript-eslint/no-unsafe-member-access": off
  "@typescript-eslint/no-unsafe-return": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/restrict-plus-operands": off
  "@typescript-eslint/no-misused-promises": off

  "@typescript-eslint/no-explicit-any": error
