---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
settings:
  react:
    version: detect
rules:
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-empty-function": off
  react/prop-types: off
  react/no-deprecated: off
